--- #outline to playbook translation
- hosts: centos
  user: test
  sudo: yes
  gather_facts: no 
  tasks:
    - name: date/time stamp for when palybook starts
      raw: /usr/bin/date > /home/test/playbook_start.log
    - name: install apsche web server 
      yum: pkg=httpd state=latest
    - name: start the web server
      service: name=httpd state=restarted
    - name: veryfiy that the service is running 
      command: systemctl status httpd
      register: result
    - debug: var=result
    - name: install client software - lynx
      yum: pkg=lynx state=latest
    - name: install client software - telnet
      yum: pkg=telnet state=latest
    - name: log all installed packages on the system
      raw: yum list installed > /home/test/installed.log
    - name: date/time stamp for when the playbook ends
      raw: /usr/bin/date > /home/playbook_end.log

      
