--- #my play book 3
- hosts: centos
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files: 
    - vars/author.yml
    - vars/defaults.yml
  tasks:
    - name: install linx web browser
      action: yum name=lynx state=installed
    - name: check if telnet is availible
      action: yum name=telnet state=absent
  
