---# my second ansible palaybook
- hosts: centos
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files: 
    - conf/author.yml
    - conf/webroot.yml
  vars_prompt: web_domain
    - name: web_domain 
      prompt: Web Domain
  