- hosts: centos
#  vars:
#    control_server: controlNode
#    web_root: /var/www/html/
  vars_files: vars.yml
   tasks: 
   - name: install Linx on App servers
     yum: pkg=python state=installed update_cache=true